### ISSUE TITLE
Network icons in the css file are not appearing correctly

### ISSUE THREAD

**Issue by Diebolik** [iconoir-icons/iconoir#267] opened 2023-03-16 09:21 UTC
## Prerequisites

* Version: v6.4.0
* Are you running from source/main: yes, from main
* Are you using a released build: no
* Operating system: Windows 10

## Step to reproduce

I am using the iconoir.css file and I want to use the network-left icon like iconoir-network-left and the network-left icon not appearing correctly. You can see in the attachment. 
All the network icons are the same.

## Additional info or screenshots

![image](https://user-images.githubusercontent.com/18147139/225571392-012e5cf2-257f-4d7b-963f-8c94a68b749c.png)

**Comment by sammarks** [comment] 2023-03-16 11:06
Duplicate of #255

**Closed** 2023-03-16 11:06 UTC
Labels: Issue
