### ISSUE TITLE
[ICON]-Request For Whatsapp

### ISSUE THREAD

**Issue by Avani981** [iconoir-icons/iconoir#377] opened 2023-11-18 05:52 UTC
## Icon Request

* Icon name:Whatsapp

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/iconoir-icons) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/iconoir-icons/iconoir/issues/377">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/iconoir-icons/iconoir/issues/377/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/iconoir-icons/iconoir/issues/377/pledge.svg">
</picture>
</a>

**Comment by paescuj** [comment] 2023-11-18 07:55
Duplicate of #369

**Closed by paescuj** 2023-11-18 07:55 UTC
Labels: icon request
