### ISSUE TITLE
[FEAT] - Iconoir library for SolidJS

### ISSUE THREAD

**Issue by Molizanee** [iconoir-icons/iconoir#471] opened 2024-08-15 12:07 UTC
- Develop a dedicated Iconoir library for SolidJS

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/iconoir-icons) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/iconoir-icons/iconoir/issues/471">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/iconoir-icons/iconoir/issues/471/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/iconoir-icons/iconoir/issues/471/pledge.svg">
</picture>
</a>

**Comment by paescuj** [comment] 2024-08-15 12:36
Thanks for opening the issue! However, this is a duplicate of #221.

**Closed by paescuj** 2024-08-15 12:36 UTC
Labels: enhancement
