### ISSUE TITLE
[ICON] Mastodon

### ISSUE THREAD

**Issue by skip2networks** [iconoir-icons/iconoir#338] opened 2023-08-10 13:25 UTC
## Icon Request

See https://mastodon.social/explore for more info about Mastodon.

* Icon name: Mastodon
* Use case: Social Media
* Screenshots of similar icons:
![image](https://github.com/iconoir-icons/iconoir/assets/141042008/5c5b7134-2837-4c75-bdfc-a74ea80e507d)

**Comment by sammarks** [comment] 2023-08-10 13:28
Duplicate of #214

**Closed by sammarks** 2023-08-10 13:28 UTC
Labels: icon request
