### ISSUE TITLE
Library broken - Error: unable to find directory entry in pubspec.yaml

### ISSUE THREAD

**Issue by pzehle** [iconoir-icons/iconoir#321] opened 2023-07-13 18:04 UTC
Won't install in XCODE

**Comment by sammarks** [comment] 2023-07-13 18:05
Sounds like a duplicate of #309.

**Closed by sammarks** 2023-07-13 18:05 UTC
Labels: Issue

**Comment by pzehle** [comment] 2023-07-13 18:06
It is a duplicate, but since it was created more than 2 months ago, and it is making the library completely unusable, I thought I would create a new issue, maybe someone knows how to make it work...
